### ISSUE TITLE
Production Mode / Build did't work well

### ISSUE THREAD

**Issue by johanguse** [blonestar/wp-theme-vite-tailwind-jit#10]
Hello there! Thank you for the nice work you've done here. 

I started testing this theme and encountered a problem with `yarn build`. It seems like the website didn't work well.

I'm using MAMP Pro with SSL, the SSL of my wesite.local was saving on MAMP folder, but i have generated another one to localhost in the theme folder:

```
Note: the local CA is not installed in the Firefox trust store.
Note: the local CA is not installed in the Java trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️

Created a new certificate valid for the following names 📜
 - "localhost"

The certificate is at "./localhost.pem" and the key at "./localhost-key.pem" ✅

It will expire on 13 July 2025
```
I also tried a fresh installation without SSL, but after running the build command, the website didn't load correctly. Do you think I did something wrong?

![image](https://user-images.githubusercontent.com/6184866/231795017-275e5edf-96bc-483e-b37e-ebad8d747e3b.png)

**Comment by johanguse** [comment]
I notice the problem was on `wp_enqueue_style` and `wp_enqueue_script` on [inc.vite.php](https://github.com/blonestar/wp-theme-vite-tailwind/blob/main/inc/inc.vite.php#L48)

I have a temporary fix for this problem. Please let me know if you want me to open a PR.

```
        if (is_array($manifest)) {

            // get array key with name contais .css and create new one with only that key
            $manifest_css = preg_grep('/\.css$/', array_keys($manifest));
            if (isset($manifest_css[0])) {
                wp_enqueue_style( 'main', DIST_URI . '/' . $manifest[$manifest_css[0]]['file'] );
            }

            // get $manifest by key regex .js
            $manifest_js = preg_grep('/\.js$/', array_keys($manifest));
            $manifest_js = implode($manifest_js);
            if (isset($manifest_js)) {
                wp_enqueue_script( 'main', DIST_URI . '/' . $manifest[$manifest_js]['file'], array(), null, true );
            }

        }
```

**Comment by blonestar** [comment]
Hi there,
Most common error is to use hmr address in your browser (eg localhost:3000) instead of your local domain but I'm glad you solved the issue you've had and make it running. Essentially it is just an example how to use Vite & Tailwind in the WP theme build process. 
Btw I'm not seeing problem with my code, it grabs assets listed in manifest.json.

![image](https://user-images.githubusercontent.com/5240133/231858762-80084988-ed59-4f22-b3e3-d0af24be9999.png)


You can also turn off manifest generation and just include files from /dist folder, it could simpler. (vite.config.js)
![image](https://user-images.githubusercontent.com/5240133/231859875-b911107c-5969-49ab-99df-b2c6266e1eae.png)

And please stay tuned as I'm preparing some forked small modern theme with full site editing but all together with Vite&Tailwind.

cheers

**Comment by guugg** [comment]
The local localhost and 127.0.0.*; there is indeed `npm run build` and the assets listed in `manifest.json` cannot be obtained, prompting `Uncaught SyntaxError: Unexpected token '*' (at main-e5639757.css?ver =6.2.2:1:1)`;



@johanguse  grateful
